---
- name: Config ELK VM with Docker
  hosts: elk
  become: true
  tasks:
# Set the vm.max_map_count to 262144
# REF : https://gist.github.com/praseodym/50bb9b6ac2b5e771c35f554671de759a

  - name: set vm.max_map_count to 262144 in sysctl
    sysctl: name={{ item.key }} value={{ item.value }}
    with_items:
    - { key: "vm.max_map_count", value: "262144" }

  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: dvwa
# sebp is the organization that made the container. elk is the container and 761 is the version.
      image: sebp/elk:761
      state: started
      published_ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes


